#pragma once

/*define supported algorithm of rtzip*/
#define HEADER_ALGORITHM_SIZE				1
#define HEADER_COMPRESS_BLCOK_SIZE			3
#define HEADER_COM_PIC_WIDTH_SIZE			4
#define HEADER_COM_PIC_HEIHT_SIZE			4
#define HEADER_SIZE_BEFORE_ADDR				(HEADER_ALGORITHM_SIZE+HEADER_COMPRESS_BLCOK_SIZE+HEADER_COM_PIC_WIDTH_SIZE+HEADER_COM_PIC_HEIHT_SIZE)

#define HEADER_COMPRESS_BLOCK_ADDR_SIZE		4


#define ALGORITHM_RLE			0
#define ALGORITHM_FASTLZ		1
#define ALGORITHM_YUV_FASTLZ	2
#define ALGORITHM_YUV			3




