# 我这边用的源是清华的，如源不是清华的注释掉下面这一行
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FissionBluetooth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FissionBluetooth

  target 'FissionBluetoothTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FissionBluetoothUITests' do
    # Pods for testing
  end

  # 💥Fission SDK
  # pod update Fission_Sdk_iOS --verbose --no-repo-update
  pod 'Fission_Sdk_iOS', git: 'https://github.com/linwear/Fission_Sdk_iOS.git' #Release
  # pod 'Fission_Sdk_iOS_PreRelease', git: 'https://github.com/linwear/Fission_Sdk_iOS_PreRelease.git' #Pre-Release
  
  pod 'QMUIKit'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'SVProgressHUD'
  pod 'BRPickerView'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'TZImagePickerController'
  pod 'SDAutoLayout'
  pod 'CocoaLumberjack'
  pod 'SGQRCode'
  pod 'CWLateralSlide'
  pod 'JXCategoryView'
  pod 'SSZipArchive'
  pod 'CHIPageControl/Fresno'
  pod 'ZLCollectionViewFlowLayout'
  pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
#  pod 'Realm'
  pod 'FSCalendar'
  pod 'UICountingLabel'
  pod 'JJException'

end
