source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FissionBluetooth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FissionBluetooth

  target 'FissionBluetoothTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FissionBluetoothUITests' do
    # Pods for testing
  end

  #pod 'Fission_Sdk_iOS', git: 'https://github.com/linwear/Fission_Sdk_iOS.git' 由于需要经常性调试新协议，该示例工程使用手动导入SDK集成方式
  pod 'QMUIKit'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'SVProgressHUD'
  pod 'BRPickerView'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'TZImagePickerController'
  pod 'SDAutoLayout'
  pod 'CocoaLumberjack'
  pod 'SGQRCode'
  pod 'CWLateralSlide'
  pod 'JXCategoryView'
  pod 'HJViewStyle'
  pod 'SSZipArchive'
  pod 'CHIPageControl/Fresno'
  pod 'ZLCollectionViewFlowLayout'
  pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
  pod 'Realm'
  pod 'FSCalendar'

end
